services:
  postgres-beautique:
    image: postgres
    hostname: postgres-beautique
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=beautique
    ports:
      - "3334:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-beautique-schema.sql:/docker-entrypoint-initdb.d/init-beautique-schema.sql
    networks:
      - beautique-network
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=docker
      - RABBITMQ_DEFAULT_PASS=docker
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - beautique-network
    volumes:
      - './rabbitmq-data:/var/lib/rabbitmq'
      - './rabbitmq-log:/var/log/rabbitmq'

networks:
  beautique-network:
    driver: bridge